POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name":"busta",
    "lastName":"busta",
    "contactNumber": 3127061823,
    "restaurantName":"Chuzos de yumbo",
    "nit": "1234", 
    "restaurantType":"Restaurant",
    "email":"busta@hotmail.com",
    "password":"prueba",
    "menu": []
    
}
####

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"gavo@hotmail.com",
    "password":"prueba"
}

####

POST http://localhost:3000/api/checkAuth
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzJmYzczM2UzMzkxNzlmNjc3YTQxOCIsInJlc3RhdXJhbnROYW1lIjoiQ2FyYW1iYSIsImlhdCI6MTY2OTYwMjUyMywiZXhwIjoxNjY5NjA2MTIzfQ.VGSr-IGviwwc9QgoOLueEnUyEjEZxm91jVKV-Meq_5k

###

PUT http://localhost:3000/api/admin
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzJmYzczM2UzMzkxNzlmNjc3YTQxOCIsInJlc3RhdXJhbnROYW1lIjoiQ2FyYW1iYSIsImlhdCI6MTY2OTYxMTU0MywiZXhwIjoxNjY5NjE1MTQzfQ.7Xnf8LDvdEWcroM00i0Rne8NPp8KWu7qCdTuCpuimk8

{
    "restaurantAdminId":"63853aa9dd8e910f41df4b72",
    "restaurantAdmin":{
        "name": "Bustamante"
    }
}

// Category ENDPOINTS
###
POST http://localhost:3000/api/menu/category
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzJmYzczM2UzMzkxNzlmNjc3YTQxOCIsInJlc3RhdXJhbnROYW1lIjoiQ2FyYW1iYSIsImlhdCI6MTY2OTYxMTU0MywiZXhwIjoxNjY5NjE1MTQzfQ.7Xnf8LDvdEWcroM00i0Rne8NPp8KWu7qCdTuCpuimk8

{
    "restaurantAdminId":"63856b4623d5312f6e2c04a7",
    "category":{
        "name": "Bustamante",
        "bannerImg": "Bustamante"

    }
}

###
DELETE http://localhost:3000/api/menu/category
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzJmYzczM2UzMzkxNzlmNjc3YTQxOCIsInJlc3RhdXJhbnROYW1lIjoiQ2FyYW1iYSIsImlhdCI6MTY2OTYxMTU0MywiZXhwIjoxNjY5NjE1MTQzfQ.7Xnf8LDvdEWcroM00i0Rne8NPp8KWu7qCdTuCpuimk8

{
    "restaurantAdminId":"63856b4623d5312f6e2c04a7",
    "categoryId": "638576a811542e249494e53f"
}

###
GET http://localhost:3000/api/menu/category
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzJmYzczM2UzMzkxNzlmNjc3YTQxOCIsInJlc3RhdXJhbnROYW1lIjoiQ2FyYW1iYSIsImlhdCI6MTY2OTYxMTU0MywiZXhwIjoxNjY5NjE1MTQzfQ.7Xnf8LDvdEWcroM00i0Rne8NPp8KWu7qCdTuCpuimk8

{
    "categoryId":"63859143a5f850b66afb243e"
}


